version: '3.8'

services:
  php-fpm:
    build:
      context: ./backend
    container_name: symfony_php
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=8.0"

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  scraper:
    build:
      context: ./scraper
    container_name: scraper_service
    volumes:
      - ./scraper:/app
    working_dir: /app
    entrypoint: ["./entrypoint.sh"]
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - db
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  db:
    image: mysql:8
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
